version: "3"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
    - "9876:8080"
    command:
    - start-dev --import-realm
    volumes:
    - ./exported-realm:/opt/keycloak/data/import