version: "3"
services:
  apisix:
    container_name: apache-apisix
    image: apache/apisix
    environment:
      APISIX_STAND_ALONE: "true"
    volumes:
    - ./apisix-conf.yaml:/usr/local/apisix/conf/apisix.yaml
    network_mode: host
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
    - "9876:8080"
    command:
    - start-dev