version: "3"
services:
  postgres:
    container_name: keycloak-postgres
    image: postgres:15.3
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "vader"
      POSTGRES_PASSWORD: "vader"
    #volumes:
    #- ./pg-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
    - "9876:8080"
    command:
    - start
    - --db postgres
    - --db-url jdbc:postgresql://postgres/keycloak
    - --db-username vader
    - --db-password vader
    - --db-schema public
    - --http-enabled true
    - --hostname-strict false
    depends_on:
    - postgres